---
- name: reboot host
  reboot:
    reboot_timeout: 180
    connect_timeout: 5
    post_reboot_delay: 30 
    test_command: whoami

- name: restart ssh
  service:
    name: ssh
    state: restarted
